### PR TITLE
Added build:dll to install script.

### PR DESCRIPTION
**Pull request by Sheyne**
As requested by @slaymaker1907

### CODE REVIEW

**Comment by RighteousRaichu** [comment]
What if we hook `npm update` instead?

**Comment by Sheyne** [comment]
That still means you have to build: dll on your initial install

**Comment by slaymaker1907** [comment]
Can we merge this soon or close the PR?

**Comment by ilargierdi** [comment]
I'm closing this, since I think the majority of us don't feel there is any benefit to the proposal.

**Pull request closed without merging**
