### PR TITLE
Ui Tweaks

### PR DESCRIPTION
**Pull request by RighteousRaichu**
I wanted to get some UI changes out the way before sending this off for the user study. Can you guys look at what I've changed and do some sanity checks to make sure nothings broken? Especially on Windows or Linux.

* Port zoom slider changes from my other branch, (continuous zooming while sliding, vertically centered)
* Round text for zoom slider.
* Associate Input/Test panels with each tab. #136
    * Hide bottom panel if no files are opened.
* Save as… Dialog #190
* #218 Warn when closing a tab if it’s unsaved… Sill a pain and can’t warn when the window is about to close.
* A bunch of changes to the way files are handled
    * #204 If you close a tab it marks the file as not changed (in the Files panel, if reopened.)	
    * Cache open files, if you ask for an open file, you get the same one. (This makes it so all references to a file are the same LocalFile) (done by making constructor private and creating a static builder)
    * Make unsaved indicator show up again in files panel and tab bar. (Angular 4 broke it I think.)
    * #240 Remember which file was selected when reopening files on startup.
    * #141 Make the tab bar not overflow it’s size. It scrolls now but the scroll bar is hidden (currently requires a mouse/trackpad that can scroll horizontally.) The new tab button is always at the right.
    * #213 Catch and log all errors when trying to resume state when reopening files. Handle in a sane way (Reopen all the other files if one has problems.) Doesn’t throw an error if the file is no longer there or if core throws an error when loading the graph.
    * When reopening, remembers the full file path. If you were to run it from a different directory it should still be able to reopen files.
* #161 Set minimum window size to 1024x720. This fits into XGA and 720p. Set startup size to 1080x768 instead of full screen. I put in issue #250 to make Electron remember what the last window size was.
* Fixed some menu events were no longer getting sent to the Graph Editor (Undo, Redo, Delete, etc...)

### CODE REVIEW

**Comment by ilargierdi** [comment]
Looks great on Windows. I noticed a couple of minor bugs, but I think they should be separate issues. I'll list them here:

* Incorrect path string on Windows:
image
  * Sidenote: I think it should ask the user if they want to save changes before closing instead of what it currently says
* Minor bug in tools panel where the last element in the list does not show as being selected (tested on circuit design)
* Looks like divisible-by-three example doesn't deselect nodes during step-through debugging

**Comment by ilargierdi** [comment]
Looks like the bug with selecting the last element in the tools panel is only happening on Windows.

On Linux, the minimum window size is too large. I can't get to the bottom of the input box, and it won't let me shrink the window height. The maximize button isn't even available. The only way for me to get to the input bar at the bottom is the go into fullscreen mode.

**Comment by RighteousRaichu** [comment]
@cj this is probably left over from the graph editor maintenance, but if you delete a node when its anchor point is showing, then when you move the mouse you're calling the validateEdgeHandler with the deleted node as the source.

**Comment by RighteousRaichu** [comment]
For,
> Looks like divisible-by-three example doesn't deselect nodes during step-through debugging
It's because master is so old it doesn't have the UUID changes yet, so nodes must have a unique label for the debugging to work.

**Comment by RighteousRaichu** [comment]
@cj is it trivial to fix the validateEdgeHandler anchorPoints issue? If so do it here, otherwise lets make an issue for it. (I've made it just log the error instead of throw it)

Also can you check again on,
* Does Tools Panel behave correctly for you?
* Does the confirm close dialog work as expected on Windows?
  * Does it display a normal looking path on Windows?
* Is the new minimum size better?
* Is the current default size OK?

**Comment by ilargierdi** [comment]
Everything looks great, with one minor detail on the Windows path: it's just missing the drive `C:`, but the rest of the path is correct.

**Comment by ilargierdi** [comment]
@RighteousRaichu let me know if my recent push works for you.

**Comment by RighteousRaichu** [comment]
@cj I'm getting a nastier bug with that so I'm going to reverse it and just create an issue for it.

**Comment by RighteousRaichu** [comment]
Nevermind it's a separate issue let me see if I can get reproduction steps for you.

**Comment by RighteousRaichu** [comment]
@cj can you fix this?
1) Open file with many nodes.
2) Select a node and delete it.
3) Select everything by dragging mouse
4) Start dragging mouse again.

```
ERROR TypeError: Cannot read property 'hitRect' of undefined
    at EditorGraph.updateSelectionBox (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1224:1), <anonymous>:354:18)
    at EditorGraph.drag (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1224:1), <anonymous>:149:26)
    at HTMLElement.GraphEditorComponent.onMouseMove (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:430:1), <anonymous>:91:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/polyfills.js:820:1), <anonymous>:398:31)
    at Object.onInvokeTask (file:///Users/daniel/Development/sinap-ide/build/vendor.bundle.js:1:90658)
    at ZoneDelegate.invokeTask (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/polyfills.js:820:1), <anonymous>:397:36)
    at Zone.runTask (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/polyfills.js:820:1), <anonymous>:165:47)
    at HTMLElement.ZoneTask.invoke (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/polyfills.js:820:1), <anonymous>:460:38)
    at 
```

**Comment by ilargierdi** [comment]
@RighteousRaichu Let me know if the bug persists on your end from my recent push.

**Comment by RighteousRaichu** [comment]
@cj that fixed that bug; however, now when I delete an edge and a node at the same time and undo, I get an error. I confirmed that this wasn't in the previous commit.

**Comment by RighteousRaichu** [comment]
(maybe because nodes are being deleted before edges now? I don't have the time to look into rn)

**Comment by ilargierdi** [comment]
I didn't change the order of deletion, so that can't be it. I'll take a
look into it in a couple of hours.

**Comment by ilargierdi** [comment]
Your intuition was correct, but it was because I wasn't reordering the elements when emitting the deleted event. It should be fixed now.

**Comment by RighteousRaichu** [comment]
@cj that does fix it

... any chance fixing the shadow when moving nodes with custom shapes is easy?

**Comment by RighteousRaichu** [comment]
@cj another bug

1) Select node with edge attached to it.
2) Hover over edge.
3) Press delete button to delete the node.

```
Uncaught TypeError: Cannot read property 'clearAnchor' of undefined
    at EditorGraph.updateHoverObject (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1224:1), <anonymous>:209:20)
    at EditorGraph.unregisterDrawable (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1224:1), <anonymous>:517:14)
    at EditorGraph.onDeleted (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:1224:1), <anonymous>:37:22)
    at DrawableGraph.dispatchEvent (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:409:1), <anonymous>:49:17)
    at DrawableGraph.delete (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:402:1), <anonymous>:170:18)
    at DrawableGraph.deleteSelected (eval at <anonymous> (file:///Users/daniel/Development/sinap-ide/build/main.js:402:1), <anonymous>:176:27)
```

**Comment by ilargierdi** [comment]
@RighteousRaichu My recent push should fix both issues.

**Pull request merged**
