### PR TITLE
Undo & Redo

### PR DESCRIPTION
**Pull request by RighteousRaichu**
It's finally almost ready, just a couple points still need to be addressed in #134

### CODE REVIEW

**Comment by ilargierdi** [comment]
I'm currently working on this, and I think I have a solution that'll work
better than what we have now.

**Comment by RighteousRaichu** [comment]
One thing I forgot is being able to undo moves. Preferable for each drag and drop event one notification is sent to graph controller containing all the elements that were moved as well as old/new location. Whatever you're refactoring see if you can work that in.

**Comment by ilargierdi** [comment]
@RighteousRaichu See if this works for you b5f2681.

**Comment by RighteousRaichu** [comment]
I think I'm going to revert back to this morning and merge that. After beta we need to rethink the way notifications works, but currently they aren't powerful enough to accomplish what we need to get done.

(For instance I think you forgot we need to be able to delete/undelete groups of elements (both edges and nodes), as well as undo moving groups of elements.) (And eventually undo changing properties of groups of elements but that's not really the graph editor's concern.)

Also just by creating nodes, edges, moving around nodes and edges, and undo'ing + redo'ing I can get the graph out of sync pretty easily with these changes.

**Comment by ilargierdi** [comment]
Drawable events do have support for what you're talking about. You just
don't get them from the controller, but you can; the undoable events just
need to be augmented for that. As for copying properties to the core
elements, that can also be easily done in the controller silently with the
changes I have in place.

**Comment by RighteousRaichu** [comment]
So currently when a group of elements are deleted, two events go out, one for nodes and one for edges. These need to be one cohesive unit to be undoable. I can't see a way to do it with the way notifications are currently setup in drawable-graph without essentially doing what I've already done in previous commits.

There's three main regressions here:
* Can't delete/undelete groups of elements.
* Plugin properties aren't retained for undeleted elements.
* Playing around with undo/redo even without deleting groups of elements eventually causes a bad state (edge with no nodes attached, etc...)

I've looked into this problem long enough that I have a good idea for how I want to change the way notifications work in order to remove the 100's of lines of buggy/will become buggy/unnecessary code from graph-controller and drawable-graph so let's just talk about it again after beta.

**Pull request merged**
