### PR TITLE
Faster modal window

### PR DESCRIPTION
**Pull request by RighteousRaichu**
@cj can you test this on Windows and Linux when you get a chance?
Mainly test to make sure lifecycle stuff hasn't broken. (Can still open new window dialog, can still close app, etc...)

### CODE REVIEW

**Comment by ilargierdi** [comment]
image
Menu bar shouldn't be there on Windows; it's also showing up on Linux. Aside from that, it works great!

**Comment by slaymaker1907** [comment]
@ilargierdi is that from the packaged version or from the development version? The menu bar must be shown on Windows if debug is enabled so that you can open up developer tools.

**Comment by ilargierdi** [comment]
Oh right. It was on the development version.

**Comment by ilargierdi** [comment]
Nevermind, it's also showing up on the packaged version for windows.
image

**Pull request merged**
