### PR TITLE
better linting

### PR DESCRIPTION
**Pull request by Sheyne**

### CODE REVIEW

**Comment by slaymaker1907** [comment]
Have you verified that Travis will fail a build if linting fails?

**Comment by Sheyne** [comment]
Yes, I have verified.

**Comment by RighteousRaichu** [comment]
Before merging this into IDE, I wanna make sure the merge with this and my branch isn't going to be too crazy.

**Comment by Sheyne** [comment]
I'm doing the rebase for you right now.

**Pull request merged**
