### PR TITLE
Graph editor images

### PR DESCRIPTION
**Pull request by ilargierdi**
* Added support for custom images
  - `Shapes` now has an additional type in its union: "image"
* Added support for custom anchor points
* Drawable nodes now have two new public fields: `image` and `anchorPoints`
  - The `image` field is a string representing the path (preferably absolute) to the image file
  - The `anchorPoints` field is a list of points
    + Points with duplicate coordinates are removed
    + The coordinates of an anchor point is relative to the upper left corner of a node

### CODE REVIEW

**Comment by ilargierdi** [comment]
Yes, I can do that tonight. Although, I think for the accept states, I'd rather just add in a new double line style for the border.

**Comment by RighteousRaichu** [comment]
Does "double" borderStyle work on nodes yet?

**Comment by ilargierdi** [comment]
Not yet

**Comment by RighteousRaichu** [comment]
Do you want to do it for this branch or should I just merge this?

**Comment by ilargierdi** [comment]
Just merge, and I'll make a separate issue for double lines.

**Pull request merged**
