### PR TITLE
Turing Machine / Input Panel Improvements

### PR DESCRIPTION
**Pull request by RighteousRaichu**
Try to play with the example TM I created and make it it's all kosher.
I also made some minor visual improvements to the input panel.

### CODE REVIEW

**Comment by ilargierdi** [comment]
I'm going to need a little more time to fix 7f9e7a9 completey, but for now, the file loads with the loopback edges bound to the top anchor point.

**Comment by ilargierdi** [comment]
4e0387f should fix the problem with bound anchor points being loaded from a saved file.

**Comment by RighteousRaichu** [comment]
Thanks! @CJ looks great!

**Comment by ilargierdi** [comment]
Ah, you merged too quickly lol
I just pushed a fix to the example file, since the plugin stuff got erased.

**Pull request merged**
