### PR TITLE
Graph editor clipboard events foundation.

### PR DESCRIPTION
**Pull request by ilargierdi**
This PR is mainly to push some changes on `main.component`. Please ensure that it works on MacOS. In particular, make sure that delete still works as expected for the editor.

* Added foundation for clipboard events on the graph editor.
  - The editor currently has no implementation of cut/copy/paste; I'm waiting for (de)serialization for the clipboard events. If this is a problem, I can probably hack a temp solution, but I'd like the changes to `main.component` to be merged into master.
* Added a couple of menu events to redirect some of the menu functionality to the editor.

### CODE REVIEW

**Comment by RighteousRaichu** [comment]
@ilargierdi look at my commit and make sure I didn't break anything for Windows.

**Comment by ilargierdi** [comment]
Your fix didn't break anything new on Windows, so it should still be good.

**Comment by RighteousRaichu** [comment]
Is selectAll still broken on Windows? (It works fine on macOS)

**Comment by ilargierdi** [comment]
Yeah, it is. Select all works fine outside of the editor, but if the editor
has focus, then nothing happens.

**Comment by RighteousRaichu** [comment]
Does it not work because `focusIsChildOf` doesn't work or for some other reason? Either lets get this fixed or create an issue for it then I'll approve.

**Comment by ilargierdi** [comment]
Your function is working just fine. My guess is that the hidden text box is
capturing the Ctrl+A keybind and halting propagation natively.

**Pull request merged**
