### PR TITLE
Circuits

### PR DESCRIPTION
**Pull request by RighteousRaichu**
Make sure nothing is borken pls

### CODE REVIEW

**Comment by ilargierdi** [comment]
How do I run the input?

**Comment by Sheyne** [comment]
Check or uncheck a box the hit enter.

**Comment by ilargierdi** [comment]
Hitting enter does nothing

**Comment by Sheyne** [comment]
Hmm at least on Mac if you give a check box focus enter works. It's wonky but probably good enough for demo. Eventually we probably want shift enter to run the input regardless of selection.

**Comment by ilargierdi** [comment]
Oh, the checkbox needs to have the focus; it works, but only if either of the check boxes have focus.

**Comment by ilargierdi** [comment]
Is the turing machine supposed to output a boolean in the input panel?

**Comment by RighteousRaichu** [comment]
Yeah, Turing Machines output whether or not they accept the language.

**Comment by ilargierdi** [comment]
Shouldn't it always return true? I think it'd be neat to show the tape as part of the output, but it's not that important for the presentation.

**Comment by Sheyne** [comment]
Formally Turing machines decide if a string is in a language. The tape is "irrelevant". For example deciding whether a number is divisible by 5, or is prime, or whatnot. Most of the time you care more about the acceptance than the tape content.

**Comment by RighteousRaichu** [comment]
I'm planning on saying something around those lines, and saying, "we can step through execution and see how the tape changes with the debugger."

**Pull request merged**
